### ISSUE TITLE
next button needs to say why it's unclickable. 

### ISSUE THREAD

**Issue by TybaltCapulet** [Xymist/ringsmiths#15]
next button when a choice hasn't been made currently doesn't do anything. We need to create an instruction for the user to say something like 'Oops, it looks like you haven't made a selection yet' if next button is currently unclickable.

**Comment by Xymist** [comment]
Is this actually best UX? Would we not do better just to hide it entirely?

**Comment by TybaltCapulet** [comment]
That's a much nicer solution. Let's do that.
