### ISSUE TITLE
Spec section

### ISSUE THREAD

**Issue by TybaltCapulet** [Xymist/ringsmiths#2]
Image should be the same as the current selection for width.

ID for image is spec-image

Text section should insert text for 'Your chosen ring is a [carat] [metal] [style] wedding ring with a finger width of [width].'.

Also text to say 'We make your rings using recycled gold and only use recycled and eco-friendly packaging materials. Click the button below to find out more about your perfect ring, including pricing and customisation options.'

[Carat] 9ct,18ct
[Metal] Yellow Gold, White Gold, Rose Gold, Platinum, Titanium
[Style] Court, D Shape, Easy Fit, Flat
[Width] 2mm, 2.5mm, 3mm, 4mm, 5mm, 6mm, 8mm

**Comment by TybaltCapulet** [comment]
Tested - changeable text needs some changes: 

No hyphens between Colour-Gold, no hyphen in d-shape or easy-fit.

d-shape to be 'D Shape'

**Comment by Xymist** [comment]
OK with easy-fit becoming "Easy Fit" and "Yellow Gold" having capitals?

**Comment by TybaltCapulet** [comment]
Yes please.
