### ISSUE TITLE
Selection of elements needs to be confirmed via border

### ISSUE THREAD

**Issue by TybaltCapulet** [Xymist/ringsmiths#4]
If an element is selected, then a 3px border needs to be put around that div.

**Comment by Oliverrackley** [comment]
If I create an 'onClick' class for the current selection, are you able to add it to the JS? So onclick > Add this class to the div > Remove class from any other div ?

**Comment by Xymist** [comment]
Yes, that's fine

**Comment by Oliverrackley** [comment]
.selectedOption {
border-width: 3px;
border-color: #f6c570;
box-shadow: 0px 2px 18px -5px #f6c570;
}

**Comment by Oliverrackley** [comment]
By the way, I've added this to the core CSS. So this '_just_' needs to be appended to the selected div.

**Comment by Xymist** [comment]
Would it be worth moving the core (and other?) CSS into a file in this repo and including it via tag, rather than pasting stuff into elements?

**Comment by Oliverrackley** [comment]
100%

**Comment by TybaltCapulet** [comment]
Well volunteered Olly...

**Comment by Oliverrackley** [comment]
LOL, If I knew how, I would

**Comment by TybaltCapulet** [comment]
Exactly why it hasn't been done already.

**Comment by Xymist** [comment]
Completed in #18
