### ISSUE TITLE
Scroll doesn't return to start position after clicking to next section on mobile

### ISSUE THREAD

**Issue by TybaltCapulet** [Xymist/ringsmiths#41]
When clicking through on a mobile section, it doesn't reset your position on the scroll, so places you randomly in the next carousel.

**Comment by Xymist** [comment]
This is one for @Oliverrackley. JS level is rendering everything at once.

**Comment by Oliverrackley** [comment]
It's not so much, random, it will place you where the previous div was in the carousel, I need to try and manipulate it so that it picks the first div child

**Comment by Xymist** [comment]
This will also need to be done in reverse, to ensure that it will always be in the right place when you click the "back" button.

**Comment by TybaltCapulet** [comment]
I think we need to reset the x axis scroll position on next/back buttons. I think we can do this with JS via setting scrollleft to 0.

@Xymist - Would you be able to check this for me please?

**Comment by Xymist** [comment]
Fixed by #45

**Comment by TybaltCapulet** [comment]
Closing as fixed.
